{% set setup = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ setup.name | lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: {{ GIT_DESCRIBE_TAG }}
  git_url: https://gitlab.com/necla-ml/ML.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - h5py
    - ignite
    - numexpr
    - pip
    - python
    - pytorch
    - pyyaml
    - pytables
    - torchvision
    - setuptools
  run:
  - accimage>=0.1.1           # [not osx]
  - av
  - blosc>=1.17
  - conda                     # [not osx]          # implicitly required by cudatoolkit-dev=10.0.*
  - conda-build
#  - cudatoolkit=10.1.*       # [not osx]          # pytorch GPU dependency even on CPU machines except macOS
#  - cudatoolkit-dev=10.1.*   # [not osx]          # separate installation for local development requiring >= 24GB tmp space
  - cython=0.29.*
  - git
  - git-lfs
  - h5py>=2.10.*
  - ignite
  - jsonpatch                 # implicitly required by visdom
  - line_profiler>=2.1.2
  - magma-cuda100>=2          # [not osx]
  - matplotlib>=3.1.1
  - pandas>=0.25.1
  - lbzip2
  - opencv
  - pigz
  - pillow<=6.2.2             # in case of mmdet
  - pip
  - psutil                    # number of physical cores
  - pycocotools>=2
  - pygments>=2.4.2
  - pytables>=3.5.2
  - pytest>=5.2.0
  - python=3.7
  - python-daemon
  - pytorch=1.4
  - pyyaml>=5.1.2
  - requests-toolbelt         # multipart streaming over HTTP
  - setuptools>=41.2
  - six>=1.12
  - scikit-learn>=0.21.3      # required by BERT
  - tensorboard>=2.1
  - torchvision
  - visdom>=0.1.8.9
  - transformers>=2.1.1
test:
  imports:
    - ml._C

about:
  home: https://gitlab.com/necla-ml/ML
  license: BSD
  license_family: BSD
  summary: Composable command line interface toolkit
