#{% set name = "ML" %}
#{% set version = "v0.1.4" %}

package:
  name: "{{ load_setup_py_data().pkg }}"
  version: "{{ load_setup_py_data().version }}"

source:
  git_rev: "v{{ load_setup_py_data().version }}"
  git_url: https://gitlab.com/necla-ml/ML.git

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - h5py
    - ignite
    - numexpr
    - pip
    - python
    - pytorch
    - pyyaml
    - pytables
    - torchvision
    - setuptools
  run:
  - accimage>=0.1.1         # [not osx]
  - av
  - blosc>=1.17
  - conda                    # [not osx]          # implicitly required by cudatoolkit-dev=10.0.*
  - conda-build
  - cudatoolkit=10.1.*       # [not osx]          # necessay for machines without GPUs except macOS
  #- cudatoolkit-dev=10.1.*  # [not osx]          # separate installation required
  - cython=0.29.*
  - git
  - git-lfs
  - h5py>=2.10.*
  - ignite
  - jsonpatch               # implicitly required by visdom
  - line_profiler>=2.1.2
  - magma-cuda100>=2.5.1    # [not osx]
  - matplotlib>=3.1.1
  - pandas>=0.25.1
  - lbzip2
  - opencv
  - pigz
  - pillow>=7
  - pip>=19.2.3
  - pycocotools>=2.0.0
  - pygments>=2.4.2
  - pytables>=3.5.2
  - pytest>=5.2.0
  - python=3.7.*
  - python-daemon
  - pytorch=1.4.*
  - pyyaml>=5.1.2
  - requests-toolbelt           # multipart streaming over HTTP
  - setuptools>=41.2.0
  - six>=1.12.0
  - scikit-learn>=0.21.3        # required by BERT
  - torchvision
  - visdom>=0.1.8.9
  - transformers>=2.1.1
test:
  imports:
    - ml
    - from ml import _C

about:
  home: https://gitlab.com/necla-ml/ML
  license: BSD
  license_family: BSD
  summary: Composable command line interface toolkit